name: CI

on: [push, pull_request]

jobs:
  python_lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.11', '3.12', '3.13'] # Added Python 3.13 to the matrix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pdm.lock'

      - name: Install dependencies
        run: |
          pip install pdm
          pdm install

      - name: Check formatting (black)
        run: black . --diff --color && black . --check

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check .


